### PR TITLE
Improve Binder and launch jupyverse directly

### LINKED ISSUE #73: Start `jupyverse` automatically on Binder
### Problem

At the moment we have to start `jupyverse` by running a couple of notebook cells on Binder:

image

Maybe should add the `jupyter-server-proxy` config to automatically run the command on startup. And use the `?urlpath=` in the Binder URL to redirect to the `jupyverse`-served frontend on startup.

### Proposed Solution

We add a `jupyter_notebook_config.py` that sets up the `jupyter-server-proxy` config.

### PR DESCRIPTION
**Pull request by davidbrochart**
Closes #73

### CODE REVIEW

**Comment by davidbrochart** [comment]
@jtpio @fcollonval you can try it here: https://mybinder.org/v2/gh/davidbrochart/jupyverse/improve_binder
IIUC it doesn't launch jupyverse directly, you need to click on jupyverse in the launcher?

**Comment by jtpio** [comment]
Probably setting `?urlpath=jupyverse` in the Binder URL will handle the redirect?

**Comment by davidbrochart** [comment]
Indeed, thanks.
Any way to not have the `?token=l8XZNQDWR-KQiuMuwQtemQ` query parameter?

**Comment by fcollonval** [comment]
> Probably setting `?urlpath=jupyverse` in the Binder URL will handle the redirect?

I thought that too but it does not work...
May be related I see that in the server log:
```
if have_lab:
    # if recent-enough lab is available, make it the default UI
    sys.argv.insert(1, "--NotebookApp.default_url=/lab/")
```

**Comment by davidbrochart** [comment]
> I thought that too but it does not work...

This works: https://mybinder.org/v2/gh/davidbrochart/jupyverse/improve_binder?urlpath=jupyverse
The problem is that jupyverse expects a UUID for the token, but here we launch it with `noauth` anyway so there should not be any token query parameter.

**Comment by fcollonval** [comment]
> This works: https://mybinder.org/v2/gh/davidbrochart/jupyverse/improve_binder?urlpath=jupyverse

I get the following answer: `{"detail":[{"loc":["query","token"],"msg":"value is not a valid uuid","type":"type_error.uuid"}]}`

Not the application

**Comment by davidbrochart** [comment]
Yes, jupyverse expects a UUID, that's why we shouldn't pass a `token` query parameter (the one from Jupyter is not a UUID).

**Comment by davidbrochart** [comment]
I guess we can allow the token to be any string.
This works now, the only thing is that it only launches the JupyterLab frontend (compared to before where we had the choice to choose RetroLab).

**Comment by davidbrochart** [comment]
Someone wants to squash and merge?

**Review by jtpio — APPROVED** [review]
Thanks!

**Comment by jtpio** [comment]
Looks good on Binder:

image

**Pull request merged**
