### PR TITLE
Add JupyterCAD plugin

### PR DESCRIPTION
**Pull request by davidbrochart**
cc @trungleduc

### CODE REVIEW

**Comment by davidbrochart** [comment]
We were thinking with @martinRenou that this could actually live in https://github.com/QuantStack/jupytercad, what do you think?

**Comment by trungleduc** [comment]
> We were thinking with @martinRenou that this could actually live in https://github.com/QuantStack/jupytercad, what do you think?

indeed I think this is a great idea. Correct me if I'm wrong, but this plugin does not import anything from `jupytercad`?

**Comment by davidbrochart** [comment]
Oh, now that you're mentioning I realize that I forgot to commit :smile:

**Comment by davidbrochart** [comment]
> this plugin does not import anything from `jupytercad`?

No.

**Comment by trungleduc** [comment]
ok, I see how it works with your latest commit. Can we move this plugin to `jupytercad` without making `jupytercad` depends on `jupyverse`?

**Comment by davidbrochart** [comment]
I opened https://github.com/QuantStack/jupytercad/pull/179 and removed the jupytercad plugin here.

**Pull request closed without merging**
