### PR TITLE
Update fastapi-users v12

### PR DESCRIPTION
**Pull request by davidbrochart**

### CODE REVIEW

**Comment by davidbrochart** [comment]
Type check [fails](https://github.com/jupyter-server/jupyverse/actions/runs/5521697680/jobs/10070191286?pr=329) with:
```
plugins/auth/fps_auth/db.py:33: error: Incompatible types in assignment (expression has type "Column[str]", base class "SQLAlchemyBaseUserTable" defined the type as "str")  [assignment]
```
It's pointing to this [line](https://github.com/jupyter-server/jupyverse/blob/a87000a3b4e95df42ba4255f29904217dec2526b/plugins/auth/fps_auth/db.py#L33) where `email` is defined:
```py
class User(SQLAlchemyBaseUserTableUUID, Base):
    anonymous = Column(Boolean, default=True, nullable=False)
    email = Column(String(length=32), nullable=False, unique=True)
   ...
```
It seems to be an SQLAlchemy issue, but maybe @frankie567 has an idea?

**Comment by frankie567** [comment]
Why do you need to redefine the `email` column? It's directly provided by `SQLAlchemyBaseUserTableUUID` (besides 32 characters is probably too short). That's why there is a type mismatch between the two.

**Comment by davidbrochart** [comment]
Ah right, it was not necessary. Thanks!

**Comment by frankie567** [comment]
Well, TIL about `AsyncAttrs`. Looks nice!

However, if you have `lazy="joined"` on the relationship arguments, oauth accounts should be loaded eagerly up-front, so you shouldn't have this error 🤔

**Comment by davidbrochart** [comment]
Mmm then I'm not sure what was going on, I might have to revisit this issue in the future.

**Pull request merged**
