### PR TITLE
Use `fps_uvicorn` plugin

### PR DESCRIPTION
**Pull request by adriendelsalle**
Description
---

https://github.com/jupyter-server/fps/pull/32 moved `uvicorn` and corresponding CLI to a dedicated plugin.

Use `fps_uvicorn` plugin:
- use config moved from fps to fps_uvicorn
- update dependencies
- use logger to print link in console

### CODE REVIEW

**Comment by davidbrochart** [comment]
`ImportError: cannot import name 'get_configured_logger' from 'fps.logging' (/usr/share/miniconda/envs/jupyverse-dev/lib/python3.9/site-packages/fps/logging.py)`
@adriendelsalle aren't we missing a FPS release?

**Comment by adriendelsalle** [comment]
I didn't released yet after merging jupyter-server/fps#32 , did you tested on master or is it only the CI output?

**Comment by davidbrochart** [comment]
`[E 2021-09-22 16:15:46 fps] Config model '<class 'fps_uvicorn.config.UvicornConfig'>' is not yet registered`

**Comment by davidbrochart** [comment]
Looks like tests pass, I could wait for an FPS release and install `fps[uvicorn]` in this PR?

**Comment by adriendelsalle** [comment]
@davidbrochart I just fixed the issue (https://github.com/jupyter-server/fps/pull/35)

Works locally, I already released `fps-uvicorn 0.0.2` and `fps 0.0.8`

**Comment by adriendelsalle** [comment]
> Looks like tests pass, I could wait for an FPS release and install `fps[uvicorn]` in this PR?

yes it should work now

**Comment by davidbrochart** [comment]
Maybe still worth keeping FPS master in the CI, as we are co-developing FPS and jupyverse?

**Comment by adriendelsalle** [comment]
It would be a good way to catch breaking changes. Up to you!

**Comment by davidbrochart** [comment]
Thanks @adriendelsalle !

**Pull request merged**
