### PR TITLE
move contents utils function to utils.py

### PR DESCRIPTION
**Pull request by Wh1isper**

### CODE REVIEW

**Comment by Wh1isper** [comment]
This PR is for other modules to import the contents interface without importing the route, thanks

**Comment by davidbrochart** [comment]
Thanks for the PR @Wh1isper.

> This PR is for other modules to import the contents interface without importing the route

This is still registering the routes though. Out of curiosity, what would you need this for?

**Comment by Wh1isper** [comment]
> Thanks for the PR @Wh1isper.
> 
> > This PR is for other modules to import the contents interface without importing the route
> 
> This is still registering the routes though. Out of curiosity, what would you need this for?

Oh I'm starting to understand, I want to use these functions in other projects but not register the router for this plugin. Maybe I can only copy the code directly..

Thanks for the reminder!

**Comment by davidbrochart** [comment]
Sure, you can copy the code. Please add some credit to Jupyverse in your projects.

**Comment by Wh1isper** [comment]
> 

Got it , thanks

**Pull request closed without merging**
